###############################---eureka---##############################
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER}/eureka/
#######e签宝
sign:
  url: https://smlo.tsign.cn/opentreaty-service
  appId: 4438758707
  appSecret: 3af57b9b79b617d6058839029184a981
  templateId: 1df9304f174a4c6a8f5ef29a5cc61362
  